name: heyto
description: Live Streaming, Private Video chat and Dating

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  #Default
  cupertino_icons: ^1.0.3
  google_fonts: ^4.0.4

  #Images
  flutter_svg: ^2.0.9
  cached_network_image: ^3.2.0
  image_picker: ^1.1.2
  image_compression_flutter: ^1.0.2
  crop: ^0.5.2
  blur: ^4.0.0
  flutter_swipecards: ^0.2.1

  #Chat
  sticky_grouped_list: ^3.1.0

  #Backend
  parse_server_sdk_flutter: ^8.0.0

  #Angopapo packages
  linear_progress_bar: ^1.1.0 #This package was developed specially for this app.

  #Utilities
  easy_localization: ^3.0.0
  flutter_native_splash: ^2.1.3+1
  path_provider: ^2.0.5
  rflutter_alert: ^2.0.2
  intl: ^0.19.0
  webview_flutter: ^4.9.0
  url_launcher: ^6.0.9
  universal_platform: ^1.0.0+1
  stop_watch_timer: ^3.1.1
  flutter_windowmanager: ^0.2.0
  devicelocale: ^0.8.1
  shared_preferences: ^2.0.6
  url_strategy: ^0.3.0
  carousel_slider: ^5.0.0
  package_info: ^2.0.2
  permission_handler: ^11.3.1
  rxdart: ^0.27.3
  share_plus: ^10.1.2
  iban: ^1.0.1
  sleek_circular_slider: ^2.0.1
  app_settings: ^5.1.1

  #Geo data and phone helper
  country_provider: ^1.0.2
  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^8.0.1
  geocoding: ^3.0.0
  location: ^7.0.1
  #google_places_flutter: ^2.0.5
  flutter_google_places_sdk: ^0.3.2+1

  #Animations
  animations: ^2.0.2
  lottie: ^3.0.0

  #Ads
  google_mobile_ads: ^5.2.0
  advertising_id: ^2.2.0
  app_tracking_transparency: ^2.0.2+1

  #Firebase
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  firebase_analytics: ^11.3.5
  firebase_performance: ^0.10.0+10
  firebase_crashlytics: ^4.1.5
  firebase_dynamic_links: ^6.0.10

  #Social login
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  google_sign_in_web: ^0.12.4+3
  sign_in_with_apple: ^6.1.3
  flutter_facebook_auth: ^6.0.4

  #gpayments:
  in_app_purchase: ^3.0.2

  #Squeleton
  fade_shimmer: ^2.0.1

  #state management
  provider: ^6.0.2
  http: ^0.13.4
  transparent_image: ^2.0.0

  #Calls and live streaming
  agora_rtc_engine: ^6.1.0
  agora_rtm: ^2.2.2
  flutter_ringtone_player: ^4.0.0+3
  flutter_sound: ^9.2.13

  #push notifications
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/card/
    - assets/images/
    - assets/translations/
    - assets/svg/
    - assets/vector/

flutter_native_splash:
  color: "#ffffff" #White color
  color_dark: "#1d1d35" # Dark color
  fullscreen: true
  image: assets/images/ic_logo.png
  image_dark: assets/images/ic_logo_white.png